namespace NexusForever.GameTable.Model
{
    public class AttributeMiniMilestoneGroupEntry
    {
        public uint Id { get; set; }
        public uint RequiredAttributeAmount00 { get; set; }
        public uint RequiredAttributeAmount01 { get; set; }
        public uint RequiredAttributeAmount02 { get; set; }
        public uint RequiredAttributeAmount03 { get; set; }
        public uint RequiredAttributeAmount04 { get; set; }
        public uint RequiredAttributeAmount05 { get; set; }
        public uint RequiredAttributeAmount06 { get; set; }
        public uint RequiredAttributeAmount07 { get; set; }
        public uint RequiredAttributeAmount08 { get; set; }
        public uint RequiredAttributeAmount09 { get; set; }
        public uint RequiredAttributeAmount10 { get; set; }
        public uint RequiredAttributeAmount11 { get; set; }
        public uint RequiredAttributeAmount12 { get; set; }
        public uint RequiredAttributeAmount13 { get; set; }
        public uint RequiredAttributeAmount14 { get; set; }
        public uint RequiredAttributeAmount15 { get; set; }
        public uint RequiredAttributeAmount16 { get; set; }
        public uint RequiredAttributeAmount17 { get; set; }
        public uint RequiredAttributeAmount18 { get; set; }
        public uint RequiredAttributeAmount19 { get; set; }
        public uint RequiredAttributeAmount20 { get; set; }
        public uint RequiredAttributeAmount21 { get; set; }
        public uint RequiredAttributeAmount22 { get; set; }
        public uint RequiredAttributeAmount23 { get; set; }
        public uint RequiredAttributeAmount24 { get; set; }
        public uint RequiredAttributeAmount25 { get; set; }
        public uint RequiredAttributeAmount26 { get; set; }
        public uint RequiredAttributeAmount27 { get; set; }
        public uint RequiredAttributeAmount28 { get; set; }
        public uint RequiredAttributeAmount29 { get; set; }
        public uint RequiredAttributeAmount30 { get; set; }
        public uint RequiredAttributeAmount31 { get; set; }
        public uint RequiredAttributeAmount32 { get; set; }
        public uint RequiredAttributeAmount33 { get; set; }
        public uint RequiredAttributeAmount34 { get; set; }
        public uint RequiredAttributeAmount35 { get; set; }
        public uint RequiredAttributeAmount36 { get; set; }
        public uint RequiredAttributeAmount37 { get; set; }
        public uint RequiredAttributeAmount38 { get; set; }
        public uint RequiredAttributeAmount39 { get; set; }
        public uint RequiredAttributeAmount40 { get; set; }
        public uint RequiredAttributeAmount41 { get; set; }
        public uint RequiredAttributeAmount42 { get; set; }
        public uint RequiredAttributeAmount43 { get; set; }
        public uint RequiredAttributeAmount44 { get; set; }
        public uint UnitProperty2IdSecondaryStat00 { get; set; }
        public uint UnitProperty2IdSecondaryStat01 { get; set; }
        public uint UnitProperty2IdSecondaryStat02 { get; set; }
        public uint UnitProperty2IdSecondaryStat03 { get; set; }
        public uint UnitProperty2IdSecondaryStat04 { get; set; }
        public uint UnitProperty2IdSecondaryStat05 { get; set; }
        public uint UnitProperty2IdSecondaryStat06 { get; set; }
        public uint UnitProperty2IdSecondaryStat07 { get; set; }
        public uint UnitProperty2IdSecondaryStat08 { get; set; }
        public uint UnitProperty2IdSecondaryStat09 { get; set; }
        public uint UnitProperty2IdSecondaryStat10 { get; set; }
        public uint UnitProperty2IdSecondaryStat11 { get; set; }
        public uint UnitProperty2IdSecondaryStat12 { get; set; }
        public uint UnitProperty2IdSecondaryStat13 { get; set; }
        public uint UnitProperty2IdSecondaryStat14 { get; set; }
        public uint UnitProperty2IdSecondaryStat15 { get; set; }
        public uint UnitProperty2IdSecondaryStat16 { get; set; }
        public uint UnitProperty2IdSecondaryStat17 { get; set; }
        public uint UnitProperty2IdSecondaryStat18 { get; set; }
        public uint UnitProperty2IdSecondaryStat19 { get; set; }
        public uint UnitProperty2IdSecondaryStat20 { get; set; }
        public uint UnitProperty2IdSecondaryStat21 { get; set; }
        public uint UnitProperty2IdSecondaryStat22 { get; set; }
        public uint UnitProperty2IdSecondaryStat23 { get; set; }
        public uint UnitProperty2IdSecondaryStat24 { get; set; }
        public uint UnitProperty2IdSecondaryStat25 { get; set; }
        public uint UnitProperty2IdSecondaryStat26 { get; set; }
        public uint UnitProperty2IdSecondaryStat27 { get; set; }
        public uint UnitProperty2IdSecondaryStat28 { get; set; }
        public uint UnitProperty2IdSecondaryStat29 { get; set; }
        public uint UnitProperty2IdSecondaryStat30 { get; set; }
        public uint UnitProperty2IdSecondaryStat31 { get; set; }
        public uint UnitProperty2IdSecondaryStat32 { get; set; }
        public uint UnitProperty2IdSecondaryStat33 { get; set; }
        public uint UnitProperty2IdSecondaryStat34 { get; set; }
        public uint UnitProperty2IdSecondaryStat35 { get; set; }
        public uint UnitProperty2IdSecondaryStat36 { get; set; }
        public uint UnitProperty2IdSecondaryStat37 { get; set; }
        public uint UnitProperty2IdSecondaryStat38 { get; set; }
        public uint UnitProperty2IdSecondaryStat39 { get; set; }
        public uint UnitProperty2IdSecondaryStat40 { get; set; }
        public uint UnitProperty2IdSecondaryStat41 { get; set; }
        public uint UnitProperty2IdSecondaryStat42 { get; set; }
        public uint UnitProperty2IdSecondaryStat43 { get; set; }
        public uint UnitProperty2IdSecondaryStat44 { get; set; }
        public float Modifier00 { get; set; }
        public float Modifier01 { get; set; }
        public float Modifier02 { get; set; }
        public float Modifier03 { get; set; }
        public float Modifier04 { get; set; }
        public float Modifier05 { get; set; }
        public float Modifier06 { get; set; }
        public float Modifier07 { get; set; }
        public float Modifier08 { get; set; }
        public float Modifier09 { get; set; }
        public float Modifier10 { get; set; }
        public float Modifier11 { get; set; }
        public float Modifier12 { get; set; }
        public float Modifier13 { get; set; }
        public float Modifier14 { get; set; }
        public float Modifier15 { get; set; }
        public float Modifier16 { get; set; }
        public float Modifier17 { get; set; }
        public float Modifier18 { get; set; }
        public float Modifier19 { get; set; }
        public float Modifier20 { get; set; }
        public float Modifier21 { get; set; }
        public float Modifier22 { get; set; }
        public float Modifier23 { get; set; }
        public float Modifier24 { get; set; }
        public float Modifier25 { get; set; }
        public float Modifier26 { get; set; }
        public float Modifier27 { get; set; }
        public float Modifier28 { get; set; }
        public float Modifier29 { get; set; }
        public float Modifier30 { get; set; }
        public float Modifier31 { get; set; }
        public float Modifier32 { get; set; }
        public float Modifier33 { get; set; }
        public float Modifier34 { get; set; }
        public float Modifier35 { get; set; }
        public float Modifier36 { get; set; }
        public float Modifier37 { get; set; }
        public float Modifier38 { get; set; }
        public float Modifier39 { get; set; }
        public float Modifier40 { get; set; }
        public float Modifier41 { get; set; }
        public float Modifier42 { get; set; }
        public float Modifier43 { get; set; }
        public float Modifier44 { get; set; }
    }
}
