namespace NexusForever.GameTable.Model
{
    public class Creature2DisplayInfoEntry
    {
        public uint Id { get; set; }
        public uint StatusFlags { get; set; }
        public string AssetPath { get; set; }
        public string AssetTexture00 { get; set; }
        public string AssetTexture01 { get; set; }
        public string AssetTexture02 { get; set; }
        public string AssetTexture03 { get; set; }
        public string AssetTexture04 { get; set; }
        public string AssetTexture05 { get; set; }
        public uint ModelTextureId00 { get; set; }
        public uint ModelTextureId01 { get; set; }
        public uint ModelTextureId02 { get; set; }
        public uint ModelTextureId03 { get; set; }
        public uint ModelTextureId04 { get; set; }
        public uint ModelTextureId05 { get; set; }
        public string ColorShiftTexturePath { get; set; }
        public uint ColorShiftTextureIdMask { get; set; }
        public uint MaterialDataIdSkinColor0 { get; set; }
        public uint MaterialDataIdSkinColor1 { get; set; }
        public uint MaterialDataIdWeaponColor0 { get; set; }
        public uint MaterialDataIdWeaponColor1 { get; set; }
        public uint MaterialDataIdArmorColor0 { get; set; }
        public uint MaterialDataIdArmorColor1 { get; set; }
        public uint MaterialDataIdDefault0 { get; set; }
        public uint MaterialDataIdDefault1 { get; set; }
        public uint CreatureMaterialEnum { get; set; }
        public float Scale { get; set; }
        public float HitRadius { get; set; }
        public float WalkLand { get; set; }
        public float WalkAir { get; set; }
        public float WalkWater { get; set; }
        public float WalkHover { get; set; }
        public float RunLand { get; set; }
        public float RunAir { get; set; }
        public float RunWater { get; set; }
        public float RunHover { get; set; }
        public uint ItemVisualTypeIdFeet { get; set; }
        public float SwimWaterDepth { get; set; }
        public uint RaceId { get; set; }
        public uint Sex { get; set; }
        public uint ItemDisplayId00 { get; set; }
        public uint ItemDisplayId01 { get; set; }
        public uint ItemDisplayId02 { get; set; }
        public uint ItemDisplayId03 { get; set; }
        public uint ItemDisplayId04 { get; set; }
        public uint ItemDisplayId05 { get; set; }
        public uint ItemDisplayId06 { get; set; }
        public uint ItemDisplayId07 { get; set; }
        public uint ItemDisplayId08 { get; set; }
        public uint ItemDisplayId09 { get; set; }
        public uint ItemDisplayId10 { get; set; }
        public uint ItemDisplayId11 { get; set; }
        public uint ItemDisplayId12 { get; set; }
        public uint ItemDisplayId13 { get; set; }
        public uint ItemDisplayId14 { get; set; }
        public uint ItemDisplayId15 { get; set; }
        public uint ItemDisplayId16 { get; set; }
        public uint ItemDisplayId17 { get; set; }
        public uint ItemDisplayId18 { get; set; }
        public uint ItemDisplayId19 { get; set; }
        public uint ModelMeshId00 { get; set; }
        public uint ModelMeshId01 { get; set; }
        public uint ModelMeshId02 { get; set; }
        public uint ModelMeshId03 { get; set; }
        public uint ModelMeshId04 { get; set; }
        public uint ModelMeshId05 { get; set; }
        public uint ModelMeshId06 { get; set; }
        public uint ModelMeshId07 { get; set; }
        public uint ModelMeshId08 { get; set; }
        public uint ModelMeshId09 { get; set; }
        public uint ModelMeshId10 { get; set; }
        public uint ModelMeshId11 { get; set; }
        public uint ModelMeshId12 { get; set; }
        public uint ModelMeshId13 { get; set; }
        public uint ModelMeshId14 { get; set; }
        public uint ModelMeshId15 { get; set; }
        public float GroundOffsetHover { get; set; }
        public float GroundOffsetFly { get; set; }
    }
}
