namespace NexusForever.GameTable.Model
{
    public class ReplaceableMaterialInfoEntry
    {
        public uint Id { get; set; }
        public uint Type { get; set; }
        public uint Flags { get; set; }
        public uint Op { get; set; }
        public uint Blend { get; set; }
        public uint ShaderNum00 { get; set; }
        public uint ShaderNum01 { get; set; }
        public uint NumLayers { get; set; }
        public uint ColorIndex01 { get; set; }
        public uint ColorIndex00 { get; set; }
        public uint ColorIndex02 { get; set; }
        public uint ColorIndex03 { get; set; }
        public uint NormalIndex00 { get; set; }
        public uint NormalIndex01 { get; set; }
        public uint NormalIndex02 { get; set; }
        public uint NormalIndex03 { get; set; }
        public uint HeightSource00 { get; set; }
        public uint HeightSource01 { get; set; }
        public uint HeightSource02 { get; set; }
        public uint HeightSource03 { get; set; }
        public uint OpacitySource00 { get; set; }
        public uint OpacitySource01 { get; set; }
        public uint OpacitySource02 { get; set; }
        public uint OpacitySource03 { get; set; }
        public uint GlossSource00 { get; set; }
        public uint GlossSource01 { get; set; }
        public uint GlossSource02 { get; set; }
        public uint GlossSource03 { get; set; }
        public uint GlowSource00 { get; set; }
        public uint GlowSource01 { get; set; }
        public uint GlowSource02 { get; set; }
        public uint GlowSource03 { get; set; }
        public uint ShaderSource00 { get; set; }
        public uint ShaderSource01 { get; set; }
        public uint ShaderSource02 { get; set; }
        public uint ShaderSource03 { get; set; }
        public float HeightValue00 { get; set; }
        public float HeightValue01 { get; set; }
        public float HeightValue02 { get; set; }
        public float HeightValue03 { get; set; }
        public float OpacityValue00 { get; set; }
        public float OpacityValue01 { get; set; }
        public float OpacityValue02 { get; set; }
        public float OpacityValue03 { get; set; }
        public float GlossValue00 { get; set; }
        public float GlossValue01 { get; set; }
        public float GlossValue02 { get; set; }
        public float GlossValue03 { get; set; }
        public float GlowValue00 { get; set; }
        public float GlowValue01 { get; set; }
        public float GlowValue02 { get; set; }
        public float GlowValue03 { get; set; }
        public float ShaderValue00 { get; set; }
        public float ShaderValue01 { get; set; }
        public float ShaderValue02 { get; set; }
        public float ShaderValue03 { get; set; }
        public float HeightScale00 { get; set; }
        public float HeightScale01 { get; set; }
        public float HeightScale02 { get; set; }
        public float HeightScale03 { get; set; }
        public float HeightOffset00 { get; set; }
        public float HeightOffset01 { get; set; }
        public float HeightOffset02 { get; set; }
        public float HeightOffset03 { get; set; }
        public float ParallaxScale00 { get; set; }
        public float ParallaxScale01 { get; set; }
        public float ParallaxScale02 { get; set; }
        public float ParallaxScale03 { get; set; }
        public float ParallaxOffset00 { get; set; }
        public float ParallaxOffset01 { get; set; }
        public float ParallaxOffset02 { get; set; }
        public float ParallaxOffset03 { get; set; }
        public uint TextureTiles00 { get; set; }
        public uint TextureTiles01 { get; set; }
        public uint TextureTiles02 { get; set; }
        public uint TextureTiles03 { get; set; }
        public float ColorModX00 { get; set; }
        public float ColorModX01 { get; set; }
        public float ColorModX02 { get; set; }
        public float ColorModX03 { get; set; }
        public float ColorModY00 { get; set; }
        public float ColorModY01 { get; set; }
        public float ColorModY02 { get; set; }
        public float ColorModY03 { get; set; }
        public float ColorModZ00 { get; set; }
        public float ColorModZ01 { get; set; }
        public float ColorModZ02 { get; set; }
        public float ColorModZ03 { get; set; }
        public uint MaterialTypeId00 { get; set; }
        public uint MaterialTypeId01 { get; set; }
        public uint MaterialTypeId02 { get; set; }
        public uint MaterialTypeId03 { get; set; }
        public string ColorTexture00 { get; set; }
        public string ColorTexture01 { get; set; }
        public string ColorTexture02 { get; set; }
        public string ColorTexture03 { get; set; }
        public string NormalTexture00 { get; set; }
        public string NormalTexture01 { get; set; }
        public string NormalTexture02 { get; set; }
        public string NormalTexture03 { get; set; }
    }
}
