namespace NexusForever.GameTable.Model
{
    public class Spell4Entry
    {
        public uint Id { get; set; }
        public string Description { get; set; }
        public uint Spell4BaseIdBaseSpell { get; set; }
        public uint TierIndex { get; set; }
        public uint RavelInstanceId { get; set; }
        public uint CastTime { get; set; }
        public uint SpellDuration { get; set; }
        public uint SpellCoolDown { get; set; }
        public float TargetMinRange { get; set; }
        public float TargetMaxRange { get; set; }
        public float TargetVerticalRange { get; set; }
        public uint CasterInnateRequirement0 { get; set; }
        public uint CasterInnateRequirement1 { get; set; }
        public uint CasterInnateRequirementValue0 { get; set; }
        public uint CasterInnateRequirementValue1 { get; set; }
        public uint CasterInnateRequirementEval0 { get; set; }
        public uint CasterInnateRequirementEval1 { get; set; }
        public uint TargetBeginInnateRequirement { get; set; }
        public uint TargetBeginInnateRequirementValue { get; set; }
        public uint TargetBeginInnateRequirementEval { get; set; }
        public uint InnateCostType0 { get; set; }
        public uint InnateCostType1 { get; set; }
        public uint InnateCost0 { get; set; }
        public uint InnateCost1 { get; set; }
        public uint InnateCostEMMId0 { get; set; }
        public uint InnateCostEMMId1 { get; set; }
        public uint ChannelInitialDelay { get; set; }
        public uint ChannelMaxTime { get; set; }
        public uint ChannelPulseTime { get; set; }
        public uint LocalizedTextIdActionBarTooltip { get; set; }
        public uint StackPriority { get; set; }
        public uint Spell4VisualGroupId { get; set; }
        public uint Spell4IdCastEvent00 { get; set; }
        public uint Spell4IdCastEvent01 { get; set; }
        public uint Spell4IdCastEvent02 { get; set; }
        public uint Spell4IdCastEvent03 { get; set; }
        public uint Spell4ReagentId00 { get; set; }
        public uint Spell4ReagentId01 { get; set; }
        public uint Spell4ReagentId02 { get; set; }
        public uint Spell4RunnerId00 { get; set; }
        public uint Spell4RunnerId01 { get; set; }
        public uint RunnerTargetTypeEnum00 { get; set; }
        public uint RunnerTargetTypeEnum01 { get; set; }
        [GameTableFieldArray(2u)]
        public uint[] PrerequisiteIdRunners { get; set; }
        public uint AbilityChargeCount { get; set; }
        public uint AbilityRechargeTime { get; set; }
        public uint AbilityRechargeCount { get; set; }
        public uint ThresholdTime { get; set; }
        public uint AbilityPointCost { get; set; }
        public uint TrainingCost { get; set; }
        public uint SpellChannelFlags { get; set; }
        public uint IgnoreFollowTimeMs { get; set; }
        public uint Spell4IdMechanicAlternateSpell { get; set; }
        public uint Spell4IdPetSwitch { get; set; }
        public uint Spell4TagId00 { get; set; }
        public uint Spell4TagId01 { get; set; }
        public uint Spell4TagId02 { get; set; }
        public uint Spell4TagId03 { get; set; }
        public uint Spell4TagId04 { get; set; }
        public uint LocalizedTextIdCasterIconSpellText { get; set; }
        public uint LocalizedTextIdPrimaryTargetIconSpellText { get; set; }
        public uint LocalizedTextIdSecondaryTargetIconSpellText { get; set; }
        public uint LocalizedTextIdLASTier { get; set; }
        public uint LocalizedTextIdTooltipCastInfo { get; set; }
        public uint LocalizedTextIdTooltipCostInfo { get; set; }
        public uint TooltipCastTime { get; set; }
        public uint Spell4AoeTargetConstraintsId { get; set; }
        public uint Spell4ConditionsIdCaster { get; set; }
        public uint Spell4ConditionsIdTarget { get; set; }
        public uint Spell4CCConditionsIdCaster { get; set; }
        public uint Spell4CCConditionsIdTarget { get; set; }
        public uint SpellCoolDownIdGlobal { get; set; }
        public uint SpellCoolDownId00 { get; set; }
        public uint SpellCoolDownId01 { get; set; }
        public uint SpellCoolDownId02 { get; set; }
        public uint Spell4GroupListId { get; set; }
        public uint MissileSpeed { get; set; }
        public uint MinMissileSpeed { get; set; }
        public uint Spell4ClientMissileId00 { get; set; }
        public uint Spell4ClientMissileId01 { get; set; }
        public uint Spell4ClientMissileId02 { get; set; }
        public uint Spell4ClientMissileId03 { get; set; }
        public uint Spell4ClientMissileId04 { get; set; }
        public uint Spell4ClientMissileId05 { get; set; }
        public uint GlobalCooldownEnum { get; set; }
        public uint PropertyFlags { get; set; }
        public uint UiFlags { get; set; }
        public uint Spell4StackGroupId { get; set; }
        public uint PrerequisiteIdCasterCast { get; set; }
        public uint PrerequisiteIdTargetCast { get; set; }
        public uint PrerequisiteIdCasterPersistence { get; set; }
        public uint PrerequisiteIdTargetPersistence { get; set; }
        public uint CastEventConditionEnum00 { get; set; }
        public uint CastEventConditionEnum01 { get; set; }
        public uint CastEventConditionEnum02 { get; set; }
        public uint CastEventConditionEnum03 { get; set; }
        public uint CastEventTargetFlags00 { get; set; }
        public uint CastEventTargetFlags01 { get; set; }
        public uint CastEventTargetFlags02 { get; set; }
        public uint CastEventTargetFlags03 { get; set; }
        public uint SpellCastStealthChange { get; set; }
        public uint PrerequisiteIdAoeTarget { get; set; }
        public uint PrerequisiteIdAoePreferredTarget { get; set; }
    }
}
