<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Message\Model\Guild\ServerGuildPerkDeactivated.cs~RFdb4915.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusForever.Game.Static\NexusForever.Game.Static.csproj" />
    <ProjectReference Include="..\NexusForever.Network\NexusForever.Network.csproj" />
  </ItemGroup>

</Project>
