namespace NexusForever.Game.Static.Abilities
{
    public enum GameCommandType
    {
        GadgetAbility          = 0x0,
        DefaultAttack          = 0x1,
        ClassInnateAbility     = 0x2,
        ActivateTarget         = 0x3,
        FollowTarget           = 0x4,
        Sprint                 = 0x5,
        ToggleWalk             = 0x6,
        //Unused1              = 0x7,
        Dismount               = 0x8,
        Vacuum                 = 0x9,
        PathAction             = 0xA,
        ToggleScannerBot       = 0xB,
        DashForward            = 0xC,
        DashBackward           = 0xD,
        DashLeft               = 0xE,
        DashRight              = 0xF,
        PathAction2            = 0x10,
        Interact               = 0x11,
        GoToBind               = 0x12,
        GoToHouse              = 0x13,
        EscapeHouse            = 0x14,
        GoToWarplot            = 0x15,
        //Unused2              = 0x16,
        WarplotBossTokenUI     = 0x17,
        //Unused3              = 0x18,
        //Unused4              = 0x19,
        SummonMount            = 0x1A,
        UsePotion              = 0x1B,
        GoToIllium             = 0x1C,
        GoToThayd              = 0x1D,
        HousingLandscape       = 0x1E,
        HousingRemodel         = 0x1F,
        HousingCrate           = 0x20,
        HousingVendor          = 0x21,
        HousingList            = 0x22,
        HousingEditMode        = 0x23,
    };
}
