namespace NexusForever.WorldServer.Game.Social.Static
{
    public enum ChatChannelType
    {
        Command = 1,
        System,
        Debug,
        Say,
        Yell,
        Whisper,
        Party,
        Emote,
        Zone,
        ZonePvP,
        Trade,
        LFG,
        Class,
        GuildRecruit,
        Guild,
        GuildOfficer,
        Society,
        Custom,
        Support,
        NPCSay,
        NPCYell,
        NPCWhisper,
        Datachron,
        Combat,
        Realm,
        Loot,
        AnimatedEmote,
        ActionEmote,
        WarParty,
        WarPartyOfficer,
        PlayerPath,
        Instance,
        Nexus,
        AccountWhisper,
        ZoneGerman,
        ZoneFrench,
        NexusGerman,
        NexusFrench,
        Community = 47
    }
}
