using NexusForever.Network.Message;
using NexusForever.Network.World.Message.Model;

namespace NexusForever.WorldServer.Network.Message.Handler.Misc
{
    public class ClientWatchdogStatisticsHandler : IMessageHandler<WorldSession, ClientWatchdogStatistics>
    {
        /// <summary>
        /// Client sends this first when joining the world server, before the player's character has been selected, and
        /// then randomly every 1-10 seconds once their character is loaded in the client.
        /// Contains statistics about the watchdog run times on the client, a random value generated by the client and its seed value.
        /// Currently no known use for this data in NF but it is useful to have a handler receive the packet.
        /// </summary>
        public void HandleMessage(WorldSession session, ClientWatchdogStatistics watchdogStatistics)
        {
        }
    }
}
