// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Query;

#nullable disable

namespace NexusForever.Database.Query.Migrations
{
    [DbContext(typeof(QueryContext))]
    partial class QueryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NexusForever.Database.Query.Model.CharacterModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("realmId");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("class");

                    b.Property<ushort>("CurrentRealmId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("currentRealmId");

                    b.Property<uint>("Faction")
                        .HasColumnType("int unsigned")
                        .HasColumnName("faction");

                    b.Property<string>("GuildName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guildName");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastOnline");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<byte>("Path")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("path");

                    b.Property<byte>("Race")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("race");

                    b.Property<string>("RealmName")
                        .HasColumnType("longtext")
                        .HasColumnName("realmName");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("sex");

                    b.Property<ushort>("WorldZoneId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("worldZoneId");

                    b.HasKey("CharacterId", "RealmId");

                    b.HasIndex("Class");

                    b.HasIndex("CurrentRealmId");

                    b.HasIndex("GuildName");

                    b.HasIndex("Level");

                    b.HasIndex("Name");

                    b.HasIndex("Path");

                    b.HasIndex("Race");

                    b.HasIndex("WorldZoneId");

                    b.ToTable("character", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
