// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Auth;

namespace NexusForever.Database.Auth.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20201119110054_RBACSignature")]
    partial class RBACSignature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountCostumeUnlockModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("itemId")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("timestamp")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id", "ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("account_costume_unlock");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountCurrencyModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<byte>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currencyId")
                        .HasColumnType("tinyint(4) unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<ulong>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("amount")
                        .HasColumnType("bigint(20) unsigned")
                        .HasDefaultValue(0ul);

                    b.HasKey("Id", "CurrencyId")
                        .HasName("PRIMARY");

                    b.ToTable("account_currency");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountEntitlementModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<byte>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("entitlementId")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<uint>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("amount")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.HasKey("Id", "EntitlementId")
                        .HasName("PRIMARY");

                    b.ToTable("account_entitlement");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountGenericUnlockModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("Entry")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("entry")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("timestamp")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id", "Entry")
                        .HasName("PRIMARY");

                    b.ToTable("account_generic_unlock");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountKeybindingModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<ushort>("InputActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inputActionId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0);

                    b.Property<uint>("Code00")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code00")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("Code01")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code01")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("Code02")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code02")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("DeviceEnum00")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("deviceEnum00")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("DeviceEnum01")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("deviceEnum01")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("DeviceEnum02")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("deviceEnum02")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("EventTypeEnum00")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("eventTypeEnum00")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("EventTypeEnum01")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("eventTypeEnum01")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("EventTypeEnum02")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("eventTypeEnum02")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("MetaKeys00")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("metaKeys00")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("MetaKeys01")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("metaKeys01")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("MetaKeys02")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("metaKeys02")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.HasKey("Id", "InputActionId")
                        .HasName("PRIMARY");

                    b.ToTable("account_keybinding");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createTime")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email")
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("GameToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gameToken")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("S")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("s")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sessionKey")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("V")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("v")
                        .HasColumnType("varchar(512)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("email");

                    b.HasIndex("GameToken")
                        .HasName("gameToken");

                    b.HasIndex("SessionKey")
                        .HasName("sessionKey");

                    b.ToTable("account");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountPermissionModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("permissionId")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.HasKey("Id", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("account_permission");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountRoleModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("roleId")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.HasKey("Id", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("account_role");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.PermissionModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("permission");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Name = "Category: Account"
                        },
                        new
                        {
                            Id = 2u,
                            Name = "Command: AccountCreate"
                        },
                        new
                        {
                            Id = 3u,
                            Name = "Command: AccountDelete"
                        },
                        new
                        {
                            Id = 15u,
                            Name = "Category: Achievement"
                        },
                        new
                        {
                            Id = 17u,
                            Name = "Command: AchievementUpdate"
                        },
                        new
                        {
                            Id = 16u,
                            Name = "Command: AchievementGrant"
                        },
                        new
                        {
                            Id = 18u,
                            Name = "Category: Broadcast"
                        },
                        new
                        {
                            Id = 19u,
                            Name = "Command: BroadcastMessage"
                        },
                        new
                        {
                            Id = 20u,
                            Name = "Category: Character"
                        },
                        new
                        {
                            Id = 21u,
                            Name = "Command: CharacterXP"
                        },
                        new
                        {
                            Id = 22u,
                            Name = "Command: CharacterLevel"
                        },
                        new
                        {
                            Id = 5u,
                            Name = "Command: CharacterSave"
                        },
                        new
                        {
                            Id = 23u,
                            Name = "Category: Currency"
                        },
                        new
                        {
                            Id = 24u,
                            Name = "Category: CurrencyAccount"
                        },
                        new
                        {
                            Id = 25u,
                            Name = "Command: CurrencyAccountAdd"
                        },
                        new
                        {
                            Id = 26u,
                            Name = "Command: CurrencyAccountList"
                        },
                        new
                        {
                            Id = 27u,
                            Name = "Category: CurrencyCharacter"
                        },
                        new
                        {
                            Id = 28u,
                            Name = "Command: CurrencyCharacterAdd"
                        },
                        new
                        {
                            Id = 29u,
                            Name = "Command: CurrencyCharacterList"
                        },
                        new
                        {
                            Id = 30u,
                            Name = "Category: Disable"
                        },
                        new
                        {
                            Id = 31u,
                            Name = "Command: DisableInfo"
                        },
                        new
                        {
                            Id = 32u,
                            Name = "Command: DisableReload"
                        },
                        new
                        {
                            Id = 33u,
                            Name = "Category: Door"
                        },
                        new
                        {
                            Id = 34u,
                            Name = "Command: DoorOpen"
                        },
                        new
                        {
                            Id = 35u,
                            Name = "Command: DoorClose"
                        },
                        new
                        {
                            Id = 36u,
                            Name = "Category: Entitlement"
                        },
                        new
                        {
                            Id = 40u,
                            Name = "Category: EntitlementAccount"
                        },
                        new
                        {
                            Id = 41u,
                            Name = "Command: EntitlementAccountAdd"
                        },
                        new
                        {
                            Id = 42u,
                            Name = "Command: EntitlementAccountList"
                        },
                        new
                        {
                            Id = 37u,
                            Name = "Category: EntitlementCharacter"
                        },
                        new
                        {
                            Id = 38u,
                            Name = "Command: EntitlementCharacterAdd"
                        },
                        new
                        {
                            Id = 39u,
                            Name = "Command: EntitlementCharacterList"
                        },
                        new
                        {
                            Id = 43u,
                            Name = "Category: Entity"
                        },
                        new
                        {
                            Id = 44u,
                            Name = "Command: EntityInfo"
                        },
                        new
                        {
                            Id = 45u,
                            Name = "Command: EntityProperties"
                        },
                        new
                        {
                            Id = 60u,
                            Name = "Category: EntityModify"
                        },
                        new
                        {
                            Id = 61u,
                            Name = "Command: EntityModifyDisplayInfo"
                        },
                        new
                        {
                            Id = 46u,
                            Name = "Category: Generic"
                        },
                        new
                        {
                            Id = 47u,
                            Name = "Command: GenericUnlock"
                        },
                        new
                        {
                            Id = 48u,
                            Name = "Command: GenericUnlockAll"
                        },
                        new
                        {
                            Id = 49u,
                            Name = "Command: GenericList"
                        },
                        new
                        {
                            Id = 4u,
                            Name = "Category: Help"
                        },
                        new
                        {
                            Id = 54u,
                            Name = "Category: House"
                        },
                        new
                        {
                            Id = 58u,
                            Name = "Command: HouseTeleport"
                        },
                        new
                        {
                            Id = 55u,
                            Name = "Category: HouseDecor"
                        },
                        new
                        {
                            Id = 56u,
                            Name = "Command: HouseDecorAdd"
                        },
                        new
                        {
                            Id = 57u,
                            Name = "Command: HouseDecorLookup"
                        },
                        new
                        {
                            Id = 59u,
                            Name = "Category: Item"
                        },
                        new
                        {
                            Id = 6u,
                            Name = "Command: ItemAdd"
                        },
                        new
                        {
                            Id = 62u,
                            Name = "Category: Movement"
                        },
                        new
                        {
                            Id = 63u,
                            Name = "Category: MovementSpline"
                        },
                        new
                        {
                            Id = 64u,
                            Name = "Command: MovementSplineAdd"
                        },
                        new
                        {
                            Id = 65u,
                            Name = "Command: MovementSplineClear"
                        },
                        new
                        {
                            Id = 66u,
                            Name = "Command: MovementSplineLaunch"
                        },
                        new
                        {
                            Id = 67u,
                            Name = "Category: MovementGenerator"
                        },
                        new
                        {
                            Id = 68u,
                            Name = "Command: MovementGeneratorDirect"
                        },
                        new
                        {
                            Id = 69u,
                            Name = "Command: MovementGeneratorRandom"
                        },
                        new
                        {
                            Id = 70u,
                            Name = "Category: Path"
                        },
                        new
                        {
                            Id = 71u,
                            Name = "Command: PathUnlock"
                        },
                        new
                        {
                            Id = 72u,
                            Name = "Command: PathActivate"
                        },
                        new
                        {
                            Id = 73u,
                            Name = "Command: PathXP"
                        },
                        new
                        {
                            Id = 74u,
                            Name = "Category: Pet"
                        },
                        new
                        {
                            Id = 75u,
                            Name = "Command: PetUnlockFlair"
                        },
                        new
                        {
                            Id = 76u,
                            Name = "Category: Quest"
                        },
                        new
                        {
                            Id = 77u,
                            Name = "Command: QuestAdd"
                        },
                        new
                        {
                            Id = 78u,
                            Name = "Command: QuestAchieve"
                        },
                        new
                        {
                            Id = 79u,
                            Name = "Command: QuestAchieveObjective"
                        },
                        new
                        {
                            Id = 80u,
                            Name = "Command: QuestObjective"
                        },
                        new
                        {
                            Id = 81u,
                            Name = "Command: QuestKill"
                        },
                        new
                        {
                            Id = 7u,
                            Name = "Category: RBAC"
                        },
                        new
                        {
                            Id = 8u,
                            Name = "Category: RBACAccount"
                        },
                        new
                        {
                            Id = 9u,
                            Name = "Category: RBACAccountPermission"
                        },
                        new
                        {
                            Id = 10u,
                            Name = "Command: RBACAccountPermissionGrant"
                        },
                        new
                        {
                            Id = 11u,
                            Name = "Command: RBACAccountPermissionRevoke"
                        },
                        new
                        {
                            Id = 12u,
                            Name = "Category: RBACAccountRole"
                        },
                        new
                        {
                            Id = 13u,
                            Name = "Command: RBACAccountRoleGrant"
                        },
                        new
                        {
                            Id = 14u,
                            Name = "Command: RBACAccountRoleRevoke"
                        },
                        new
                        {
                            Id = 83u,
                            Name = "Category: Spell"
                        },
                        new
                        {
                            Id = 84u,
                            Name = "Command: SpellAdd"
                        },
                        new
                        {
                            Id = 85u,
                            Name = "Command: SpellCast"
                        },
                        new
                        {
                            Id = 86u,
                            Name = "Command: SpellResetCooldown"
                        },
                        new
                        {
                            Id = 50u,
                            Name = "Category: Teleport"
                        },
                        new
                        {
                            Id = 51u,
                            Name = "Command: TeleportCoordinates"
                        },
                        new
                        {
                            Id = 52u,
                            Name = "Command: TeleportLocation"
                        },
                        new
                        {
                            Id = 53u,
                            Name = "Command: TeleportName"
                        },
                        new
                        {
                            Id = 87u,
                            Name = "Category: Title"
                        },
                        new
                        {
                            Id = 88u,
                            Name = "Command: TitleAdd"
                        },
                        new
                        {
                            Id = 89u,
                            Name = "Command: TitleRevoke"
                        },
                        new
                        {
                            Id = 90u,
                            Name = "Command: TitleAll"
                        },
                        new
                        {
                            Id = 91u,
                            Name = "Command: TitleNone"
                        },
                        new
                        {
                            Id = 92u,
                            Name = "Command: ItemLookup"
                        },
                        new
                        {
                            Id = 82u,
                            Name = "Category: Realm"
                        },
                        new
                        {
                            Id = 94u,
                            Name = "Command: RealmMOTD"
                        },
                        new
                        {
                            Id = 95u,
                            Name = "Category: Story"
                        },
                        new
                        {
                            Id = 96u,
                            Name = "Command: StoryPanel"
                        },
                        new
                        {
                            Id = 97u,
                            Name = "Command: StoryCommunicator"
                        },
                        new
                        {
                            Id = 98u,
                            Name = "Category: Reputation"
                        },
                        new
                        {
                            Id = 99u,
                            Name = "Command: ReputationUpdate"
                        },
                        new
                        {
                            Id = 10000u,
                            Name = "Other: InstantLogout"
                        },
                        new
                        {
                            Id = 10001u,
                            Name = "Other: Signature"
                        });
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.RoleModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("Flags")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flags")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Flags = 1u,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2u,
                            Flags = 1u,
                            Name = "GameMaster"
                        },
                        new
                        {
                            Id = 3u,
                            Flags = 2u,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 4u,
                            Flags = 2u,
                            Name = "Console"
                        },
                        new
                        {
                            Id = 5u,
                            Flags = 2u,
                            Name = "WebSocket"
                        });
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.RolePermissionModel", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.Property<uint>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("permissionId")
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u);

                    b.HasKey("Id", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permission");
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.ServerMessageModel", b =>
                {
                    b.Property<byte>("Index")
                        .HasColumnName("index")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("Language")
                        .HasColumnName("language")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("message")
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    b.HasKey("Index", "Language")
                        .HasName("PRIMARY");

                    b.ToTable("server_message");

                    b.HasData(
                        new
                        {
                            Index = (byte)0,
                            Language = (byte)0,
                            Message = @"Welcome to this NexusForever server!
Visit: https://github.com/NexusForever/NexusForever"
                        },
                        new
                        {
                            Index = (byte)0,
                            Language = (byte)1,
                            Message = @"Willkommen auf diesem NexusForever server!
Besuch: https://github.com/NexusForever/NexusForever"
                        });
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.ServerModel", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("host")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("127.0.0.1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("NexusForever");

                    b.Property<ushort>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("port")
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)24000);

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.ToTable("server");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Host = "127.0.0.1",
                            Name = "NexusForever",
                            Port = (ushort)24000,
                            Type = (byte)0
                        });
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountCostumeUnlockModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountCostumeUnlock")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_costume_item_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountCurrencyModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountCurrency")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_currency_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountEntitlementModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountEntitlement")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_entitlement_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountGenericUnlockModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountGenericUnlock")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_generic_unlock_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountKeybindingModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountKeybinding")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_keybinding_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountPermissionModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountPermission")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_permission_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Auth.Model.PermissionModel", "Permission")
                        .WithMany("AccountPermission")
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK__account_permission_permission_id__permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.AccountRoleModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.AccountModel", "Account")
                        .WithMany("AccountRole")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__account_role_id__account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Auth.Model.RoleModel", "Role")
                        .WithMany("AccountRole")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__account_role_role_id__role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusForever.Database.Auth.Model.RolePermissionModel", b =>
                {
                    b.HasOne("NexusForever.Database.Auth.Model.RoleModel", "Role")
                        .WithMany("RolePermission")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__role_permission_id__role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Auth.Model.PermissionModel", "Permission")
                        .WithMany("RolePermission")
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK__role_permission_permission_id__permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
