namespace NexusForever.Game.Static.Housing
{
    public enum HousingResult
    {
        Success                                     = 0, // Not used, and complains if sent to the client
        Failed                                      = 1,
        Neighbour_PlayerNotFound                    = 3,
        Neighbour_PlayerNotOnline                   = 4,
        Neighbour_PlayerNotAHomeowner               = 5,
        Neighbour_PlayerDoesntExist                 = 6,
        Neighbour_InvalidNeighbour                  = 7,
        Neighbour_AlreadyNeighbours                 = 8,
        Neighbour_NoPendingInvite                   = 9,
        Neighbour_PlayerWrongFaction                = 10,
        Neighbour_Full                              = 11,
        Neighbour_RequestTimedOut                   = 12,
        Neighbour_RequestDeclined                   = 13,
        InvalidPermissions                          = 14,
        Visit_InvalidWorld                          = 15,
        Neighbour_RequestAccepted                   = 16,
        Guild_TransactionFailed                     = 17,
        Guild_NotMember                             = 18,
        Neighbour_InvitePending                     = 19,
        Decor_InvalidPosition                       = 20,
        Decor_CannotAfford                          = 21,
        Decor_ExceedsDecorLimit                     = 22,
        Visit_Failed                                = 23,
        Decor_CouldNotValidate                      = 24,
        Decor_PrereqNotMet                          = 25,
        Visit_Private                               = 26,
        Visit_Ignored                               = 27,
        Decor_CannotCreateDecor                     = 28,
        Decor_CannotModifyDecor                     = 29,
        Decor_CannotDeleteDecor                     = 30,
        Decor_InvalidDecor                          = 31,
        Plug_PrereqNotMet                           = 32,
        Plug_InvalidPlug                            = 33,
        Plug_CannotAfford                           = 34,
        Plug_ModifyFailed                           = 35,
        Plug_MustBeUnique                           = 36,
        Plug_NotActive                              = 37,
        InvalidResidence                            = 38,
        InvalidNeighbourhood                        = 39,
        Plug_CannotRotate                           = 41,
        Decor_MustBeUnique                          = 42,
        Neighbour_PlayerIsIgnored                   = 43,
        Neighbour_IgnoredByPlayer                   = 44,
        Decor_CannotOwnMore                         = 45,
        Neighbour_MissingEntitlement                = 46,
        InvalidResidenceName                        = 47,
        MustHaveResidenceName                       = 48,
        Neighbour_PrivilegeRestricted               = 49,
        Community_ResidenceQueuedForPlacement       = 50,
        Community_AllPlotsOccupied                  = 53,
        Decor_CannotDonate                          = 54,
        Community_ResidenceNotPlacedInYourCommunity = 55,
        Community_NotInACommunity                   = 56,   
        Community_ReservationSuccess                = 57,
        Community_PlotAlreadyReserved               = 58,
        Community_PlotCurrentlyOccupied             = 59,
        Community_PlotReservationRevoked            = 60,
        Decor_ExceedsCommunityDecorLimit            = 61,
        CommunityNotFound                           = 62,
        InsufficientFunds                           = 65
    }
}