namespace NexusForever.Shared.Network.Message
{
    public enum GameMessageOpcode
    {
        State                           = 0x0000,
        State2                          = 0x0001,
        ServerHello                     = 0x0003,
        ServerMaxCharacterLevelAchieved = 0x0036,
        ServerPlayerEnteredWorld        = 0x0061,
        ServerAuthEncrypted             = 0x0076,
        ServerCharacterLogoutStart      = 0x0092,
        ServerChangeWorld               = 0x00AD,
        ClientVendorPurchase            = 0x00BE,
        ClientCharacterLogout           = 0x00BF,
        ClientHousingResidencePrivacyLevel = 0x00C9,
        ServerCharacterCreate           = 0x00DC,
        ServerChannelUpdateLoot         = 0x00DD,
        Server00F1                      = 0x00F1, // handler sends 0x00D5 and ClientPlayerMovementSpeedUpdate
        ServerCharacterFlagsUpdated     = 0x00FE,
        Server0104                      = 0x0104, // Galactic Archive
        ServerHousingPrivacy            = 0x010E,
        ServerCharacter                 = 0x010F, // single character
        ServerItemAdd                   = 0x0111,
        ServerCharacterList             = 0x0117,
        ServerMountUnlocked             = 0x0129,
        ServerItemDelete                = 0x0148,
        ClientItemDelete                = 0x0149,
        ServerCharacterSelectFail       = 0x0162,
        Server0169                      = 0x0169, // ability book related
        ServerShowActionBar             = 0x016C,
        ClientItemSplit                 = 0x017D,
        ServerItemStackCountUpdate      = 0x017F,
        ClientItemMove                  = 0x0182,
        ClientEntitySelect              = 0x0185,
        ServerFlightPathUpdate          = 0x0188,
        ServerPlayerTitleUpdate         = 0x018B,
        ServerPlayerChanged             = 0x019B,
        Server019D                      = 0x019D, // action set related
        ServerStanceChanged             = 0x019F,
        Server01A0                      = 0x01A0, // ability book related
        Server01A3                      = 0x01A3, // AMP
        ServerExperienceGained          = 0x01AC,
        ServerChatJoin                  = 0x01BC,
        ClientChat                      = 0x01C3,
        ServerChatAccept                = 0x01C2,
        ServerChat                      = 0x01C8,
        Server0237                      = 0x0237, // UI related, opens or closes different UI windows (bank, barber, ect...)
        ClientPing                      = 0x0241,
        ClientEncrypted                 = 0x0244,
        ServerCombatLog                 = 0x0247,
        ClientCharacterCreate           = 0x025B,
        ServerPlayerCreate              = 0x025E,
        ClientPacked                    = 0x025C, // the same as ClientEncrypted except the contents isn't encrypted?
        ServerEntityCreate              = 0x0262,
        ClientCharacterDelete           = 0x0352,
        ServerQuestInit                 = 0x035F,
        ClientEmote                     = 0x037E,
        Server03AA                      = 0x03AA, // friendship account related
        Server03BE                      = 0x03BE, // friendship related
        ServerRealmEncrypted            = 0x03DC,
        ServerRealmInfo                 = 0x03DB,
        ClientCheat                     = 0x03E0,
        Server0497                      = 0x0497, // guild info
        ServerHousingResidenceDecor     = 0x04DE,
        ServerHousingProperties         = 0x04DF,
        ServerHousingPlots              = 0x04E1,
        ClientHousingCrateAllDecor      = 0x04EC,
        ServerHousingNeighbors          = 0x0507,
        ServerHousingVendorList         = 0x0508,
        ClientHousingRemodel            = 0x050A,
        ClientHousingDecorUpdate        = 0x050B,
        ClientHousingPlugUpdate         = 0x0510,
        ClientHousingVendorList         = 0x0525,
        ClientHousingRenameProperty     = 0x0529,
        ClientHousingVisit              = 0x0531,
        ClientHousingEditMode           = 0x053C,
        ServerSpellList                 = 0x0551,
        ServerItemSwap                  = 0x0568,
        ServerItemMove                  = 0x0569,
        Server0570                      = 0x0570, // keybind related
        ClientHelloRealm                = 0x058F,
        ServerAuthAccepted              = 0x0591,
        ClientHelloAuth                 = 0x0592,
        ServerMovementControl           = 0x0636, // handler sends 0x0635 and 0x063A
        ServerAvailableMail             = 0x05A3,
        ClientEntityCommand             = 0x0637, // bidirectional? packet has both read and write handlers 
        ServerEntityCommand             = 0x0638, // bidirectional? packet has both read and write handlers
        ClientPlayerMovementSpeedUpdate = 0x063B,
        ServerOwnedCommodityOrders      = 0x064C,
        ServerOwnedItemAuctions         = 0x064D,
        ServerPathLog                   = 0x06BC,
        ServerRealmList                 = 0x0761, // bidirectional? packet has both read and write handlers
        ServerRealmMessages             = 0x0763,
        ClientRealmList                 = 0x07A4,
        ClientCharacterList             = 0x07E0,
        ClientVendor                    = 0x07EA,
        ClientCharacterSelect           = 0x07DD,
        ClientStorefrontRequestCatalog  = 0x082D,
        Server0854                      = 0x0854, // crafting schematic
        Server0856                      = 0x0856, // tradeskills
        Server086F                      = 0x086F,
        ServerEntityDestory             = 0x088C, // 0x8A5??
        Server08B3                      = 0x08B3,
        ServerVendor                    = 0x090B,
        ServerPlayerCurrencyChanged     = 0x0919,
        ServerItemVisualUpdate          = 0x0933,
        ServerEntityStatUpdate          = 0x0935, // 0x0938??
        Server0934                      = 0x0934,
        ServerEmote                     = 0x093C,
        ClientWhoRequest                = 0x0959,
        ServerWhoResponse               = 0x095A,
        ServerAccountEntitlements       = 0x0968
    }
}
