namespace NexusForever.WorldServer.Game.Entity.Static
{
    public enum Entitlement
    {
        CostumeSlots                                = 3,
        WarplotAccess                               = 4,
        CoreTester                                  = 5,
        TestBuff                                    = 6,
        TestTitle                                   = 7,
        TestAchievement                             = 8,
        TwoStepVerification                         = 9,
        BaseCharacterProgressionCaps                = 10,
        BaseCharacterSlots                          = 12,
        BaseCurrencyCaps                            = 14,
        EconomyParticipation                        = 15,
        GuildsAccess                                = 16,
        FullSocialParticipation                     = 17,
        CREDDUsage                                  = 18,
        InGameCSAccess                              = 19,
        Signature                                   = 22,
        ExtraAuctions                               = 23,
        ExtraCommodityOrders                        = 25,
        ExtraDecorSlots                             = 26,
        ExtraBankSlots                              = 27,
        Free                                        = 31,
        LoyaltyBonusCoordinateCraftingRadius        = 32,
        CosmicRewardOminbitDropRate                 = 35,
        AdditionalCostumeUnlocks                    = 36,
        CosmicRewardIncreasedReputationGain         = 37,
        FullGuildsAccess                            = 38,
        CosmicRewardCircruitBoardCraftingBonus      = 39,
        WakeHereCooldownReduction                   = 41,
        LoyaltyExtraCommodityOrders                 = 42,
        LoyaltyExtraAuctions                        = 43,
        LoyaltyChallengeBonus                       = 44,
        LoyaltyRestXpBonus                          = 45,
        CosmicRewardHarvestingBoost                 = 46,
        DNTVIPTier                                  = 48,
        FraudCheck                                  = 49,
        TitleHonoredInitialTesterImmortal           = 55,
        TitleHonoredInitialTesterOriginalFury       = 56,
        TitleHonoredInitialTesterMasterofSteel      = 57,
        TitleHonoredInitialTesterBladewind          = 58,
        TitleHonoredInitialTesterRedmoonRobber      = 59,
        TitleHonoredInternalTesterRotostarConqueror = 60,
        ChuaWarriorUnlock                           = 61,
        AurinEngineerUnlock                         = 62,
        CanPurchasePromotionToken                   = 63,
        TitleTheArctester                           = 64,
        ExtraSupplySatchelSlots                     = 71,
        SharedRealmBankUnlock                       = 74,
        SharedRealmBankSlots                        = 75
    }
}
