namespace NexusForever.WorldServer.Game.Entity.Static
{
    public enum EntityType
    {
        NonPlayer = 0,
        Chest = 1,
        Destructible = 2,
        Vehicle = 3,
        Door = 4,
        HarvestUnit = 5,
        CorpseUnit = 6,
        Mount = 7,
        CollectableUnit = 8,
        Taxi = 9,
        Simple = 10,
        Platform = 11,
        MailBox = 12,
        AiTurret = 13,
        InstancePortal,
        Plug,
        Residence,
        StructuredPlug,
        PinataLoot,
        BindPoint,
        Player = 20,
        Hidden,
        Trigger,
        Ghost,
        Pet,
        EsperPet,
        WorldUnit,
        ScannerUnit,
        Camera,
        Trap,
        Destructibledoor,
        Pickup,
        SimpleCollidable,
        HousingMannequin,
        HousingHarvestPlug,
        HousingPlant,
        Lockbox
    }
}
