namespace NexusForever.WorldServer.Game.Entity.Static
{
    public enum ItemSlot
    {
        ArmorChest                  = 1,
        ArmorLegs                   = 2,
        ArmorHead                   = 3,
        ArmorShoulder               = 4,
        ArmorFeet                   = 5,
        ArmorHands                  = 6,
        WeaponTool                  = 7,
        WeaponPrimary               = 20,
        BodySkin                    = 24,
        BodyFace                    = 25,
        BodyEye                     = 26,
        BodyEar                     = 27,
        BodyHair                    = 28,
        BodyTatoo                   = 29,
        BodyTail                    = 30,
        BodyHand                    = 31,
        BodyFacialHair              = 39,
        ArmorShields                = 43,
        ArmorGadget                 = 46,
        Bag                         = 47,
        GuildStandardScanLines      = 52,
        GuildStandardTrim           = 53,
        GuildStandardBackgroundIcon = 54,
        GuildStandardForegroundIcon = 55,
        GuildStandardChest          = 56,
        ArmorWeaponAttachment       = 57,
        ArmorSystem                 = 58,
        ArmorAugment                = 59,
        ArmorImplant                = 60,
        GuildStandardBack           = 61,
        GuildStandardShoulderL      = 62,
        GuildStandardShoulderR      = 63,
        EngineerMechSuit            = 64,
        Mount                       = 65,
        MountFront                  = 66,
        MountBack                   = 67,
        MountLeft                   = 68,
        MountRight                  = 69,
        BodyType                    = 70,
        WeaponArmCannon             = 71
    }
}
