namespace NexusForever.Shared.GameTable.Model
{
    public class Creature2ModelInfoEntry
    {
        public uint Id;
        public string AssetPath;
        public string AssetTexture0;
        public string AssetTexture1;
        public uint ModelTextureId0;
        public uint ModelTextureId1;
        public uint CreatureMaterialEnum;
        public float Scale;
        public float HitRadius;
        public float WalkLand;
        public float WalkAir;
        public float WalkWater;
        public float WalkHover;
        public float RunLand;
        public float RunAir;
        public float RunWater;
        public float RunHover;
        public uint ItemVisualTypeIdFeet;
        public float SwimWaterDepth;
        public uint Race;
        public uint Sex;
        public uint ItemDisplayId00;
        public uint ItemDisplayId01;
        public uint ItemDisplayId02;
        public uint ItemDisplayId03;
        public uint ItemDisplayId04;
        public uint ItemDisplayId05;
        public uint ItemDisplayId06;
        public uint ItemDisplayId07;
        public uint ItemDisplayId08;
        public uint ItemDisplayId09;
        public uint ItemDisplayId10;
        public uint ItemDisplayId11;
        public uint ItemDisplayId12;
        public uint ItemDisplayId13;
        public uint ItemDisplayId14;
        public uint ItemDisplayId15;
        public uint ItemDisplayId16;
        public uint ItemDisplayId17;
        public uint ItemDisplayId18;
        public uint ItemDisplayId19;
        public uint ModelMeshId00;
        public uint ModelMeshId01;
        public uint ModelMeshId02;
        public uint ModelMeshId03;
        public uint ModelMeshId04;
        public uint ModelMeshId05;
        public uint ModelMeshId06;
        public uint ModelMeshId07;
        public uint ModelMeshId08;
        public uint ModelMeshId09;
        public uint ModelMeshId10;
        public uint ModelMeshId11;
        public uint ModelMeshId12;
        public uint ModelMeshId13;
        public uint ModelMeshId14;
        public uint ModelMeshId15;
        public float GroundOffsetHover;
        public float GroundOffsetFly;
    }
}
