namespace NexusForever.Shared.GameTable.Model
{
    public class Spell4ClientMissileEntry
    {
        public uint Id;
        public uint MissileType;
        public uint CastStage;
        public uint OriginUnitEnum;
        public uint TargetFlags;
        public string ModelPath;
        public string FxPath;
        public string BeamPath;
        public uint BeamSource;
        public uint BeamTarget;
        public uint ItemSlot;
        public uint CostumeSide;
        public uint ModelAttachmentIdCaster;
        public uint ModelAttachmentIdTarget;
        public uint ClientDelay;
        public uint ModelEventIdDelayedBy;
        public uint Flags;
        public uint Duration;
        public uint Frequency;
        public uint SpeedMps;
        public float AccMpss;
        public uint RevolverNestedMissileInitDelay;
        public uint RevolverNestedMissileSubDelay;
        public uint Spell4ClientMissileIdNested;
        public string RevolverMissileImpactAssetPath;
        public uint MissileRevolverTrackId;
        public string BirthAnchorPath;
        public string DeathAnchorPath;
        public string TrajAnchorPath;
        public float BirthDuration;
        public float BirthAnchorAngleMin;
        public float BirthAnchorAngleMax;
        public float DeathAnchorAngleMin;
        public float DeathAnchorAngleMax;
        public uint DeathAnchorSpace;
        public uint ItemSlotIdObj;
        public uint ObjCostumeSide;
        public float TrajPoseFullBlendDistance;
        public float TrajAnchorPlaySpeed;
        public float ParabolaHeightScale;
        public float RotateX;
        public float RotateY;
        public float RotateZ;
        public float Scale;
        public float EndScale;
        public uint PhaseFlags;
        public uint TelegraphDamageIdAttach;
        public uint SoundEventIdBirth;
        public uint SoundEventIdLoopStart;
        public uint SoundEventIdLoopStop;
        public uint SoundEventIdDeath;
        public uint BeamDiffuseColor;
        public uint MissileDiffuseColor;
    }
}
