namespace NexusForever.Game.Static.Matching
{
    public enum MatchingQueueResult
    {
        InQueue                        = 0,
        InGame                         = 1,
        Level                          = 2,
        GroupSize                      = 3,
        TypeMismatch                   = 4,
        OfflineGroupMember             = 5,
        Role                           = 6,
        NotInGroup                     = 7,
        GroupMemberMatching            = 8,
        InvalidGame                    = 9,
        InvalidTeamMember              = 10,
        Left                           = 11,
        Declined                       = 12,
        CannotQueueSoloAndGroup        = 13,
        UnableToQueue                  = 14,
        RemovedByServer                = 15,
        Kicked                         = 16,
        Requeueing                     = 17,
        CannotKickYourself             = 18,
        KickAlreadyActive              = 19,
        PersonalKickCooldown           = 20,
        NotQueued                      = 21,
        NotConfirmingRole              = 22,
        NotWaitingToAccept             = 23,
        GlobalKickCooldown             = 24,
        CannotKickInCombat             = 25,
        OnlyOneServerGroupAllowed      = 26,
        UNUSED27                       = 27,
        UNUSED28                       = 28,
        SurrenderAlreadyActive         = 29,
        PersonalSurrenderCooldown      = 30,
        GlobalSurrenderCooldown        = 31,
        CannotSurrenderInCombat        = 32,
        SurrenderPermissionDenied      = 33,
        NotEligibleForRandom           = 34,
        Surrendered                    = 35,
        UNUSED36                       = 36,
        UNUSED37                       = 37,
        DungeonPrerequisite            = 38,
        VoteKick_MustBeOnWorld         = 40,
        VoteKick_GroupLootAvailable    = 41,
        Surrender_MustBeOnWorld        = 42,
        Surrender_GroupLootAvailable   = 43,
        PrivilegeRestricted            = 44,
        GroupMemberPrivilegeRestricted = 45,
        VoteKick_Disabled              = 46,
        InvalidRequeueType             = 47,
        PrimeLevelNotAchieved          = 48,
        RandomQueueRequired            = 49,
        CannotQueueCrossFaction        = 50,
        RequiresFullGroup              = 51
    }
}
