using NexusForever.Game.Static;
using NexusForever.GameTable.Model;

namespace NexusForever.GameTable
{
    public interface IGameTableManager
    {
        GameTable<AccountCurrencyTypeEntry> AccountCurrencyType { get; }
        GameTable<AccountItemEntry> AccountItem { get; }
        GameTable<AccountItemCooldownGroupEntry> AccountItemCooldownGroup { get; }
        GameTable<AchievementEntry> Achievement { get; }
        GameTable<AchievementCategoryEntry> AchievementCategory { get; }
        GameTable<AchievementChecklistEntry> AchievementChecklist { get; }
        GameTable<AchievementGroupEntry> AchievementGroup { get; }
        GameTable<AchievementSubGroupEntry> AchievementSubGroup { get; }
        GameTable<AchievementTextEntry> AchievementText { get; }
        GameTable<ActionBarShortcutSetEntry> ActionBarShortcutSet { get; }
        GameTable<ActionSlotPrereqEntry> ActionSlotPrereq { get; }
        GameTable<ArchiveArticleEntry> ArchiveArticle { get; }
        GameTable<ArchiveCategoryEntry> ArchiveCategory { get; }
        GameTable<ArchiveEntryEntry> ArchiveEntry { get; }
        GameTable<ArchiveEntryUnlockRuleEntry> ArchiveEntryUnlockRule { get; }
        GameTable<ArchiveLinkEntry> ArchiveLink { get; }
        GameTable<AttributeMilestoneGroupEntry> AttributeMilestoneGroup { get; }
        GameTable<AttributeMiniMilestoneGroupEntry> AttributeMiniMilestoneGroup { get; }
        GameTable<BindPointEntry> BindPoint { get; }
        GameTable<BinkMovieEntry> BinkMovie { get; }
        GameTable<BinkMovieSubtitleEntry> BinkMovieSubtitle { get; }
        GameTable<BugCategoryEntry> BugCategory { get; }
        GameTable<BugSubcategoryEntry> BugSubcategory { get; }
        GameTable<CCStateAdditionalDataEntry> CCStateAdditionalData { get; }
        GameTable<CCStateDiminishingReturnsEntry> CCStateDiminishingReturns { get; }
        GameTable<CCStatesEntry> CCStates { get; }
        GameTable<ChallengeEntry> Challenge { get; }
        GameTable<ChallengeTierEntry> ChallengeTier { get; }
        GameTable<CharacterCreationEntry> CharacterCreation { get; }
        GameTable<CharacterCreationArmorSetEntry> CharacterCreationArmorSet { get; }
        GameTable<CharacterCreationPresetEntry> CharacterCreationPreset { get; }
        GameTable<CharacterCustomizationEntry> CharacterCustomization { get; }
        GameTable<CharacterCustomizationLabelEntry> CharacterCustomizationLabel { get; }
        GameTable<CharacterCustomizationSelectionEntry> CharacterCustomizationSelection { get; }
        GameTable<CharacterTitleEntry> CharacterTitle { get; }
        GameTable<CharacterTitleCategoryEntry> CharacterTitleCategory { get; }
        GameTable<ChatChannelEntry> ChatChannel { get; }
        GameTable<CinematicEntry> Cinematic { get; }
        GameTable<CinematicRaceEntry> CinematicRace { get; }
        GameTable<CityDirectionEntry> CityDirection { get; }
        GameTable<ClassEntry> Class { get; }
        GameTable<ClassSecondaryStatBonusEntry> ClassSecondaryStatBonus { get; }
        GameTable<ClientEventEntry> ClientEvent { get; }
        GameTable<ClientEventActionEntry> ClientEventAction { get; }
        GameTable<ClientSideInteractionEntry> ClientSideInteraction { get; }
        GameTable<ColorShiftEntry> ColorShift { get; }
        GameTable<CombatRewardEntry> CombatReward { get; }
        GameTable<CommunicatorMessagesEntry> CommunicatorMessages { get; }
        GameTable<ComponentRegionEntry> ComponentRegion { get; }
        GameTable<ComponentRegionRectEntry> ComponentRegionRect { get; }
        GameTable<CostumeSpeciesEntry> CostumeSpecies { get; }
        GameTable<Creature2Entry> Creature2 { get; }
        GameTable<Creature2ActionEntry> Creature2Action { get; }
        GameTable<Creature2ActionSetEntry> Creature2ActionSet { get; }
        GameTable<Creature2ActionTextEntry> Creature2ActionText { get; }
        GameTable<Creature2AffiliationEntry> Creature2Affiliation { get; }
        GameTable<Creature2ArcheTypeEntry> Creature2ArcheType { get; }
        GameTable<Creature2DifficultyEntry> Creature2Difficulty { get; }
        GameTable<Creature2DisplayGroupEntryEntry> Creature2DisplayGroupEntry { get; }
        GameTable<Creature2DisplayInfoEntry> Creature2DisplayInfo { get; }
        GameTable<Creature2ModelInfoEntry> Creature2ModelInfo { get; }
        GameTable<Creature2OutfitGroupEntryEntry> Creature2OutfitGroupEntry { get; }
        GameTable<Creature2OutfitInfoEntry> Creature2OutfitInfo { get; }
        GameTable<Creature2OverridePropertiesEntry> Creature2OverrideProperties { get; }
        GameTable<Creature2ResistEntry> Creature2Resist { get; }
        GameTable<Creature2TierEntry> Creature2Tier { get; }
        GameTable<CreatureLevelEntry> CreatureLevel { get; }
        GameTable<CurrencyTypeEntry> CurrencyType { get; }
        GameTable<CustomerSurveyEntry> CustomerSurvey { get; }
        GameTable<CustomizationParameterEntry> CustomizationParameter { get; }
        GameTable<CustomizationParameterMapEntry> CustomizationParameterMap { get; }
        GameTable<DailyLoginRewardEntry> DailyLoginReward { get; }
        GameTable<DatacubeEntry> Datacube { get; }
        GameTable<DatacubeVolumeEntry> DatacubeVolume { get; }
        GameTable<DistanceDamageModifierEntry> DistanceDamageModifier { get; }
        GameTable<DyeColorRampEntry> DyeColorRamp { get; }
        GameTable<EldanAugmentationEntry> EldanAugmentation { get; }
        GameTable<EldanAugmentationCategoryEntry> EldanAugmentationCategory { get; }
        GameTable<EmotesEntry> Emotes { get; }
        GameTable<EmoteSequenceTransitionEntry> EmoteSequenceTransition { get; }
        GameTable<EntitlementEntry> Entitlement { get; }
        GameTable<EpisodeEntry> Episode { get; }
        GameTable<EpisodeQuestEntry> EpisodeQuest { get; }
        GameTable<Faction2Entry> Faction2 { get; }
        GameTable<Faction2RelationshipEntry> Faction2Relationship { get; }
        GameTable<FinishingMoveDeathVisualEntry> FinishingMoveDeathVisual { get; }
        GameTable<FullScreenEffectEntry> FullScreenEffect { get; }
        GameTable<GameFormulaEntry> GameFormula { get; }
        GameTable<GenericMapEntry> GenericMap { get; }
        GameTable<GenericMapNodeEntry> GenericMapNode { get; }
        GameTable<GenericStringGroupsEntry> GenericStringGroups { get; }
        GameTable<GenericUnlockEntryEntry> GenericUnlockEntry { get; }
        GameTable<GenericUnlockSetEntry> GenericUnlockSet { get; }
        GameTable<GossipEntryEntry> GossipEntry { get; }
        GameTable<GossipSetEntry> GossipSet { get; }
        GameTable<GuildPerkEntry> GuildPerk { get; }
        GameTable<GuildPermissionEntry> GuildPermission { get; }
        GameTable<GuildStandardPartEntry> GuildStandardPart { get; }
        GameTable<HazardEntry> Hazard { get; }
        GameTable<HookAssetEntry> HookAsset { get; }
        GameTable<HookTypeEntry> HookType { get; }
        GameTable<HousingBuildEntry> HousingBuild { get; }
        GameTable<HousingContributionInfoEntry> HousingContributionInfo { get; }
        GameTable<HousingContributionTypeEntry> HousingContributionType { get; }
        GameTable<HousingDecorInfoEntry> HousingDecorInfo { get; }
        GameTable<HousingDecorLimitCategoryEntry> HousingDecorLimitCategory { get; }
        GameTable<HousingDecorTypeEntry> HousingDecorType { get; }
        GameTable<HousingMannequinPoseEntry> HousingMannequinPose { get; }
        GameTable<HousingMapInfoEntry> HousingMapInfo { get; }
        GameTable<HousingNeighborhoodInfoEntry> HousingNeighborhoodInfo { get; }
        GameTable<HousingPlotInfoEntry> HousingPlotInfo { get; }
        GameTable<HousingPlotTypeEntry> HousingPlotType { get; }
        GameTable<HousingPlugItemEntry> HousingPlugItem { get; }
        GameTable<HousingPropertyInfoEntry> HousingPropertyInfo { get; }
        GameTable<HousingResidenceInfoEntry> HousingResidenceInfo { get; }
        GameTable<HousingResourceEntry> HousingResource { get; }
        GameTable<HousingWallpaperInfoEntry> HousingWallpaperInfo { get; }
        GameTable<HousingWarplotBossTokenEntry> HousingWarplotBossToken { get; }
        GameTable<HousingWarplotPlugInfoEntry> HousingWarplotPlugInfo { get; }
        GameTable<InputActionEntry> InputAction { get; }
        GameTable<InputActionCategoryEntry> InputActionCategory { get; }
        GameTable<InstancePortalEntry> InstancePortal { get; }
        GameTable<Item2Entry> Item { get; }
        GameTable<Item2CategoryEntry> Item2Category { get; }
        GameTable<Item2FamilyEntry> Item2Family { get; }
        GameTable<Item2TypeEntry> Item2Type { get; }
        GameTable<ItemBudgetEntry> ItemBudget { get; }
        GameTable<ItemColorSetEntry> ItemColorSet { get; }
        GameTable<ItemDisplayEntry> ItemDisplay { get; }
        GameTable<ItemDisplaySourceEntryEntry> ItemDisplaySourceEntry { get; }
        GameTable<ItemImbuementEntry> ItemImbuement { get; }
        GameTable<ItemImbuementRewardEntry> ItemImbuementReward { get; }
        GameTable<ItemProficiencyEntry> ItemProficiency { get; }
        GameTable<ItemQualityEntry> ItemQuality { get; }
        GameTable<ItemRandomStatEntry> ItemRandomStat { get; }
        GameTable<ItemRandomStatGroupEntry> ItemRandomStatGroup { get; }
        GameTable<ItemRuneInstanceEntry> ItemRuneInstance { get; }
        GameTable<ItemSetEntry> ItemSet { get; }
        GameTable<ItemSetBonusEntry> ItemSetBonus { get; }
        GameTable<ItemSlotEntry> ItemSlot { get; }
        GameTable<ItemSpecialEntry> ItemSpecial { get; }
        GameTable<ItemStatEntry> ItemStat { get; }
        GameTable<LanguageEntry> Language { get; }
        GameTable<LevelDifferentialAttributeEntry> LevelDifferentialAttribute { get; }
        GameTable<LevelUpUnlockEntry> LevelUpUnlock { get; }
        GameTable<LevelUpUnlockTypeEntry> LevelUpUnlockType { get; }
        GameTable<LiveEventEntry> LiveEvent { get; }
        GameTable<LiveEventDisplayItemEntry> LiveEventDisplayItem { get; }
        GameTable<LoadingScreenTipEntry> LoadingScreenTip { get; }
        GameTable<LocalizedEnumEntry> LocalizedEnum { get; }
        GameTable<LocalizedTextEntry> LocalizedText { get; }
        GameTable<LootPinataInfoEntry> LootPinataInfo { get; }
        GameTable<LootSpellEntry> LootSpell { get; }
        GameTable<LuaEventEntry> LuaEvent { get; }
        GameTable<MapContinentEntry> MapContinent { get; }
        GameTable<MapZoneEntry> MapZone { get; }
        GameTable<MapZoneHexEntry> MapZoneHex { get; }
        GameTable<MapZoneHexGroupEntry> MapZoneHexGroup { get; }
        GameTable<MapZoneHexGroupEntryEntry> MapZoneHexGroupEntry { get; }
        GameTable<MapZoneNemesisRegionEntry> MapZoneNemesisRegion { get; }
        GameTable<MapZonePOIEntry> MapZonePOI { get; }
        GameTable<MapZoneSpriteEntry> MapZoneSprite { get; }
        GameTable<MapZoneWorldJoinEntry> MapZoneWorldJoin { get; }
        GameTable<MatchingGameMapEntry> MatchingGameMap { get; }
        GameTable<MatchingGameTypeEntry> MatchingGameType { get; }
        GameTable<MatchingRandomRewardEntry> MatchingRandomReward { get; }
        GameTable<MatchTypeRewardRotationContentEntry> MatchTypeRewardRotationContent { get; }
        GameTable<MaterialDataEntry> MaterialData { get; }
        GameTable<MaterialRemapEntry> MaterialRemap { get; }
        GameTable<MaterialSetEntry> MaterialSet { get; }
        GameTable<MaterialTypeEntry> MaterialType { get; }
        GameTable<MiniMapMarkerEntry> MiniMapMarker { get; }
        GameTable<MissileRevolverTrackEntry> MissileRevolverTrack { get; }
        GameTable<ModelAttachmentEntry> ModelAttachment { get; }
        GameTable<ModelBoneEntry> ModelBone { get; }
        GameTable<ModelBonePriorityEntry> ModelBonePriority { get; }
        GameTable<ModelBoneSetEntry> ModelBoneSet { get; }
        GameTable<ModelCameraEntry> ModelCamera { get; }
        GameTable<ModelClusterEntry> ModelCluster { get; }
        GameTable<ModelEventEntry> ModelEvent { get; }
        GameTable<ModelEventVisualJoinEntry> ModelEventVisualJoin { get; }
        GameTable<ModelMeshEntry> ModelMesh { get; }
        GameTable<ModelPoseEntry> ModelPose { get; }
        GameTable<ModelSequenceEntry> ModelSequence { get; }
        GameTable<ModelSequenceByModeEntry> ModelSequenceByMode { get; }
        GameTable<ModelSequenceBySeatPostureEntry> ModelSequenceBySeatPosture { get; }
        GameTable<ModelSequenceByWeaponEntry> ModelSequenceByWeapon { get; }
        GameTable<ModelSequenceTransitionEntry> ModelSequenceTransition { get; }
        GameTable<ModelSkinFXEntry> ModelSkinFX { get; }
        GameTable<PathEpisodeEntry> PathEpisode { get; }
        GameTable<PathExplorerActivateEntry> PathExplorerActivate { get; }
        GameTable<PathExplorerAreaEntry> PathExplorerArea { get; }
        GameTable<PathExplorerDoorEntry> PathExplorerDoor { get; }
        GameTable<PathExplorerDoorEntranceEntry> PathExplorerDoorEntrance { get; }
        GameTable<PathExplorerNodeEntry> PathExplorerNode { get; }
        GameTable<PathExplorerPowerMapEntry> PathExplorerPowerMap { get; }
        GameTable<PathExplorerScavengerClueEntry> PathExplorerScavengerClue { get; }
        GameTable<PathExplorerScavengerHuntEntry> PathExplorerScavengerHunt { get; }
        GameTable<PathLevelEntry> PathLevel { get; }
        GameTable<PathMissionEntry> PathMission { get; }
        GameTable<PathRewardEntry> PathReward { get; }
        GameTable<PathScientistCreatureInfoEntry> PathScientistCreatureInfo { get; }
        GameTable<PathScientistDatacubeDiscoveryEntry> PathScientistDatacubeDiscovery { get; }
        GameTable<PathScientistExperimentationEntry> PathScientistExperimentation { get; }
        GameTable<PathScientistExperimentationPatternEntry> PathScientistExperimentationPattern { get; }
        GameTable<PathScientistFieldStudyEntry> PathScientistFieldStudy { get; }
        GameTable<PathScientistScanBotProfileEntry> PathScientistScanBotProfile { get; }
        GameTable<PathScientistSpecimenSurveyEntry> PathScientistSpecimenSurvey { get; }
        GameTable<PathSettlerHubEntry> PathSettlerHub { get; }
        GameTable<PathSettlerImprovementEntry> PathSettlerImprovement { get; }
        GameTable<PathSettlerImprovementGroupEntry> PathSettlerImprovementGroup { get; }
        GameTable<PathSettlerInfrastructureEntry> PathSettlerInfrastructure { get; }
        GameTable<PathSettlerMayorEntry> PathSettlerMayor { get; }
        GameTable<PathSettlerSheriffEntry> PathSettlerSheriff { get; }
        GameTable<PathSoldierActivateEntry> PathSoldierActivate { get; }
        GameTable<PathSoldierAssassinateEntry> PathSoldierAssassinate { get; }
        GameTable<PathSoldierEventEntry> PathSoldierEvent { get; }
        GameTable<PathSoldierEventWaveEntry> PathSoldierEventWave { get; }
        GameTable<PathSoldierSWATEntry> PathSoldierSWAT { get; }
        GameTable<PathSoldierTowerDefenseEntry> PathSoldierTowerDefense { get; }
        GameTable<PeriodicQuestGroupEntry> PeriodicQuestGroup { get; }
        GameTable<PeriodicQuestSetEntry> PeriodicQuestSet { get; }
        GameTable<PeriodicQuestSetCategoryEntry> PeriodicQuestSetCategory { get; }
        GameTable<PetFlairEntry> PetFlair { get; }
        GameTable<PlayerNotificationTypeEntry> PlayerNotificationType { get; }
        GameTable<PositionalRequirementEntry> PositionalRequirement { get; }
        GameTable<PrerequisiteEntry> Prerequisite { get; }
        GameTable<PrerequisiteTypeEntry> PrerequisiteType { get; }
        GameTable<PrimalMatrixNodeEntry> PrimalMatrixNode { get; }
        GameTable<PrimalMatrixRewardEntry> PrimalMatrixReward { get; }
        GameTable<PropAdditionalDetailEntry> PropAdditionalDetail { get; }
        GameTable<PublicEventEntry> PublicEvent { get; }
        GameTable<PublicEventCustomStatEntry> PublicEventCustomStat { get; }
        GameTable<PublicEventDepotEntry> PublicEventDepot { get; }
        GameTable<PublicEventObjectiveEntry> PublicEventObjective { get; }
        GameTable<PublicEventObjectiveBombDeploymentEntry> PublicEventObjectiveBombDeployment { get; }
        GameTable<PublicEventObjectiveGatherResourceEntry> PublicEventObjectiveGatherResource { get; }
        GameTable<PublicEventObjectiveStateEntry> PublicEventObjectiveState { get; }
        GameTable<PublicEventRewardModifierEntry> PublicEventRewardModifier { get; }
        GameTable<PublicEventStatDisplayEntry> PublicEventStatDisplay { get; }
        GameTable<PublicEventTeamEntry> PublicEventTeam { get; }
        GameTable<PublicEventVirtualItemDepotEntry> PublicEventVirtualItemDepot { get; }
        GameTable<PublicEventVoteEntry> PublicEventVote { get; }
        GameTable<PvPRatingFloorEntry> PvPRatingFloor { get; }
        GameTable<Quest2Entry> Quest2 { get; }
        GameTable<Quest2DifficultyEntry> Quest2Difficulty { get; }
        GameTable<Quest2RandomTextLineJoinEntry> Quest2RandomTextLineJoin { get; }
        GameTable<Quest2RewardEntry> Quest2Reward { get; }
        GameTable<QuestCategoryEntry> QuestCategory { get; }
        GameTable<QuestDirectionEntry> QuestDirection { get; }
        GameTable<QuestDirectionEntryEntry> QuestDirectionEntry { get; }
        GameTable<QuestGroupEntry> QuestGroup { get; }
        GameTable<QuestHubEntry> QuestHub { get; }
        GameTable<QuestObjectiveEntry> QuestObjective { get; }
        GameTable<RaceEntry> Race { get; }
        GameTable<RandomPlayerNameEntry> RandomPlayerName { get; }
        GameTable<RandomTextLineEntry> RandomTextLine { get; }
        GameTable<RandomTextLineSetEntry> RandomTextLineSet { get; }
        GameTable<RealmDataCenterEntry> RealmDataCenter { get; }
        GameTable<RedactedEntry> Redacted { get; }
        GameTable<ReplaceableMaterialInfoEntry> ReplaceableMaterialInfo { get; }
        GameTable<ResourceConversionEntry> ResourceConversion { get; }
        GameTable<ResourceConversionGroupEntry> ResourceConversionGroup { get; }
        GameTable<RewardPropertyEntry> RewardProperty { get; }
        GameTable<RewardPropertyPremiumModifierEntry> RewardPropertyPremiumModifier { get; }
        GameTable<RewardRotationContentEntry> RewardRotationContent { get; }
        GameTable<RewardRotationEssenceEntry> RewardRotationEssence { get; }
        GameTable<RewardRotationItemEntry> RewardRotationItem { get; }
        GameTable<RewardRotationModifierEntry> RewardRotationModifier { get; }
        GameTable<RewardTrackEntry> RewardTrack { get; }
        GameTable<RewardTrackRewardsEntry> RewardTrackRewards { get; }
        GameTable<SalvageEntry> Salvage { get; }
        GameTable<SalvageExceptionEntry> SalvageException { get; }
        GameTable<SkyCloudSetEntry> SkyCloudSet { get; }
        GameTable<SkyTrackCloudSetEntry> SkyTrackCloudSet { get; }
        GameTable<SoundBankEntry> SoundBank { get; }
        GameTable<SoundCombatLoopEntry> SoundCombatLoop { get; }
        GameTable<SoundContextEntry> SoundContext { get; }
        GameTable<SoundDirectionalAmbienceEntry> SoundDirectionalAmbience { get; }
        GameTable<SoundEnvironmentEntry> SoundEnvironment { get; }
        GameTable<SoundEventEntry> SoundEvent { get; }
        GameTable<SoundImpactEventsEntry> SoundImpactEvents { get; }
        GameTable<SoundMusicSetEntry> SoundMusicSet { get; }
        GameTable<SoundParameterEntry> SoundParameter { get; }
        GameTable<SoundStatesEntry> SoundStates { get; }
        GameTable<SoundSwitchEntry> SoundSwitch { get; }
        GameTable<SoundUIContextEntry> SoundUIContext { get; }
        GameTable<SoundZoneKitEntry> SoundZoneKit { get; }
        GameTable<Spell4Entry> Spell4 { get; }
        GameTable<Spell4AoeTargetConstraintsEntry> Spell4AoeTargetConstraints { get; }
        GameTable<Spell4BaseEntry> Spell4Base { get; }
        GameTable<Spell4CastResultEntry> Spell4CastResult { get; }
        GameTable<Spell4CCConditionsEntry> Spell4CCConditions { get; }
        GameTable<Spell4ClientMissileEntry> Spell4ClientMissile { get; }
        GameTable<Spell4ConditionsEntry> Spell4Conditions { get; }
        GameTable<Spell4EffectGroupListEntry> Spell4EffectGroupList { get; }
        GameTable<Spell4EffectModificationEntry> Spell4EffectModification { get; }
        GameTable<Spell4EffectsEntry> Spell4Effects { get; }
        GameTable<Spell4GroupListEntry> Spell4GroupList { get; }
        GameTable<Spell4HitResultsEntry> Spell4HitResults { get; }
        GameTable<Spell4ModificationEntry> Spell4Modification { get; }
        GameTable<Spell4PrerequisitesEntry> Spell4Prerequisites { get; }
        GameTable<Spell4ReagentEntry> Spell4Reagent { get; }
        GameTable<Spell4RunnerEntry> Spell4Runner { get; }
        GameTable<Spell4ServiceTokenCostEntry> Spell4ServiceTokenCost { get; }
        GameTable<Spell4SpellTypesEntry> Spell4SpellTypes { get; }
        GameTable<Spell4StackGroupEntry> Spell4StackGroup { get; }
        GameTable<Spell4TagEntry> Spell4Tag { get; }
        GameTable<Spell4TargetAngleEntry> Spell4TargetAngle { get; }
        GameTable<Spell4TargetMechanicsEntry> Spell4TargetMechanics { get; }
        GameTable<Spell4TelegraphEntry> Spell4Telegraph { get; }
        GameTable<Spell4ThresholdsEntry> Spell4Thresholds { get; }
        GameTable<Spell4TierRequirementsEntry> Spell4TierRequirements { get; }
        GameTable<Spell4ValidTargetsEntry> Spell4ValidTargets { get; }
        GameTable<Spell4VisualEntry> Spell4Visual { get; }
        GameTable<Spell4VisualGroupEntry> Spell4VisualGroup { get; }
        GameTable<SpellCoolDownEntry> SpellCoolDown { get; }
        GameTable<SpellEffectTypeEntry> SpellEffectType { get; }
        GameTable<SpellLevelEntry> SpellLevel { get; }
        GameTable<SpellPhaseEntry> SpellPhase { get; }
        GameTable<Spline2Entry> Spline2 { get; }
        GameTable<Spline2NodeEntry> Spline2Node { get; }
        GameTable<StoreDisplayInfoEntry> StoreDisplayInfo { get; }
        GameTable<StoreKeywordEntry> StoreKeyword { get; }
        GameTable<StoreLinkEntry> StoreLink { get; }
        GameTable<StoryPanelEntry> StoryPanel { get; }
        GameTable<TargetGroupEntry> TargetGroup { get; }
        GameTable<TargetMarkerEntry> TargetMarker { get; }
        GameTable<TaxiNodeEntry> TaxiNode { get; }
        GameTable<TaxiRouteEntry> TaxiRoute { get; }
        GameTable<TelegraphDamageEntry> TelegraphDamage { get; }
        GameTable<TicketCategoryEntry> TicketCategory { get; }
        GameTable<TicketSubCategoryEntry> TicketSubCategory { get; }
        GameTable<TrackingSlotEntry> TrackingSlot { get; }
        GameTable<TradeskillEntry> Tradeskill { get; }
        GameTable<TradeskillAchievementLayoutEntry> TradeskillAchievementLayout { get; }
        GameTable<TradeskillAchievementRewardEntry> TradeskillAchievementReward { get; }
        GameTable<TradeskillAdditiveEntry> TradeskillAdditive { get; }
        GameTable<TradeskillBonusEntry> TradeskillBonus { get; }
        GameTable<TradeskillCatalystEntry> TradeskillCatalyst { get; }
        GameTable<TradeskillCatalystOrderingEntry> TradeskillCatalystOrdering { get; }
        GameTable<TradeskillHarvestingInfoEntry> TradeskillHarvestingInfo { get; }
        GameTable<TradeskillMaterialEntry> TradeskillMaterial { get; }
        GameTable<TradeskillMaterialCategoryEntry> TradeskillMaterialCategory { get; }
        GameTable<TradeskillProficiencyEntry> TradeskillProficiency { get; }
        GameTable<TradeskillSchematic2Entry> TradeskillSchematic2 { get; }
        GameTable<TradeskillTalentTierEntry> TradeskillTalentTier { get; }
        GameTable<TradeskillTierEntry> TradeskillTier { get; }
        GameTable<TutorialEntry> Tutorial { get; }
        GameTable<TutorialAnchorEntry> TutorialAnchor { get; }
        GameTable<TutorialLayoutEntry> TutorialLayout { get; }
        GameTable<TutorialPageEntry> TutorialPage { get; }
        GameTable<UnitProperty2Entry> UnitProperty2 { get; }
        GameTable<UnitRaceEntry> UnitRace { get; }
        GameTable<UnitVehicleEntry> UnitVehicle { get; }
        GameTable<VeteranTierEntry> VeteranTier { get; }
        GameTable<VirtualItemEntry> VirtualItem { get; }
        GameTable<VisualEffectEntry> VisualEffect { get; }
        GameTable<VitalEntry> Vital { get; }
        GameTable<WaterSurfaceEffectEntry> WaterSurfaceEffect { get; }
        GameTable<WindEntry> Wind { get; }
        GameTable<WindSpawnEntry> WindSpawn { get; }
        GameTable<WordFilterEntry> WordFilter { get; }
        GameTable<WorldEntry> World { get; }
        GameTable<WorldClutterEntry> WorldClutter { get; }
        GameTable<WorldLayerEntry> WorldLayer { get; }
        GameTable<WorldLocation2Entry> WorldLocation2 { get; }
        GameTable<WorldSkyEntry> WorldSky { get; }
        GameTable<WorldSocketEntry> WorldSocket { get; }
        GameTable<WorldWaterEnvironmentEntry> WorldWaterEnvironment { get; }
        GameTable<WorldWaterFogEntry> WorldWaterFog { get; }
        GameTable<WorldWaterLayerEntry> WorldWaterLayer { get; }
        GameTable<WorldWaterTypeEntry> WorldWaterType { get; }
        GameTable<WorldWaterWakeEntry> WorldWaterWake { get; }
        GameTable<WorldZoneEntry> WorldZone { get; }
        GameTable<XpPerLevelEntry> XpPerLevel { get; }
        GameTable<ZoneCompletionEntry> ZoneCompletion { get; }

        TextTable TextEnglish { get; }
        TextTable TextFrench { get; }
        TextTable TextGerman { get; }

        void Initialise();

        /// <summary>
        /// Return the <see cref="TextTable"/> for the specified <see cref="Game.Static.Language"/>.
        /// </summary>
        TextTable GetTextTable(Language language);
    }
}