namespace NexusForever.WorldServer.Game.Static
{
    public enum GenericError
    {
        Ok                              = 0,
        Params,
        PlayerBusy,
        UnknownTargetUnit,
        TargetFaction,
        DbFailure,
        Item_BadId,
        Reserved02,
        Reserved03,
        Reserved04,
        Vendor_StackSize                = 11,
        Vendor_SoldOut                  = 13,
        Vendor_UnknownItem,
        Vendor_FailedPreReq,
        Vendor_NotAVendor,
        Vendor_TooFar,
        Vendor_BadItemRec,
        Vendor_NotEnoughToFillQuantity,
        Vendor_NotEnoughCash,
        Vendor_UniqueConstraint,
        Vendor_ItemLocked,
        Vendor_IWontBuyThat,
        Vendor_NoQuantity,
        Vendor_BagIsNotEmpty,
        Item_OverFlowChestCreated,
        Item_InventoryFull              = 27,
        Item_UnknownItem,
        Item_QuestViolation,
        Item_Unique,
        Item_NotValidforSlot,
        Item_Locked,
        Item_AlreadyEquipped,
        Item_NotEquipped,
        Item_BagMustBeEmpty,
        Item_CannotFindBag,
        Item_BagToSmall,
        Item_CantPutBagInItself,
        Item_WrongRace,
        Item_WrongClass,
        Item_FailedProficiency,
        Item_LevelToLow,
        Embark_PlayerAlreadyinSeat,
        Embark_PlayerUnableToEmbark,
        Embark_InvalidVehicleUnit,
        Embark_NoSplineForTaxi,
        Embark_VehicleIsBroken,
        Embark_InvalidSeat,
        Embark_SeatTaken,
        Embark_SeatEmpty,
        Embark_NotInRange,
        Embark_CannotDoWhileOnTaxi,
        Mail_CannotFindPlayer           = 53,
        Mail_FailedToCreate             = 54,
        Vendor_CuratorOnlyBuysRelics,
        Vendor_CannotBuyRelics,
        Player_CantDoWhileDead,
        Vendor_NoBuyer,
        Vendor_NoVendor,
        Vendor_Buyer_NoActionCC,
        Vendor_Vendor_NoActionCC,
        Vendor_Vendor_Disposition,
        Player_CannotWhileInCombat      = 63,
        Mail_Busy                       = 64,
        Mail_MailBoxOutOfRange          = 65,
        Mail_NoAttachment               = 66,
        Mail_InsufficientFunds          = 67,
        Mail_InvalidInventorySlot       = 68,
        Mail_UniqueExists               = 69,
        Mail_CannotDelete               = 70,
        Mail_DoesNotExist               = 71,
        Item_CannotBeSalvaged,
        Conversion_BadConversionRec,
        Conversion_CannotRemoveSource,
        Conversion_CannotAddTarget,
        Faction_NotEnoughRep,
        Item_NoItems,
        Craft_TierTooLow,
        Craft_MissingMaterials,
        Craft_IncompleteCircuit,
        UnlockItemFailed,
        Craft_DuplicateChip,
        DisEmbark_PlayerNotInWorld,
        Item_NeedsRepair,
        Craft_TooManyAdditives,
        Item_SlotDisabled,
        Matching_NoRoleSelected,
        Instance_NotFound,
        Auction_NotReady,
        Auction_CannotFillOrder,
        Mail_CannotTransferItem         = 91,
        Mail_InvalidText                = 92,
        Mail_CanNotHaveCoDAndGift       = 93,
        Auction_TooManyOrders,
        Auction_OrderTooBig,
        Auction_NotFound,
        Auction_BidTooLow,
        Auction_OwnItem,
        Auction_BidTooHigh,
        Auction_AlreadyHasBid,
        Mail_InvalidDeliverySpeed       = 101,
        Housing_InvalidDecorPlacement   = 103,
        Instance_LimitExceeded          = 110,
        Craft_UnknownSchematic,
        Craft_MicrochipInvalidSocket,
        UNUSED113,
        Craft_FailChanceTooHigh,
        Instance_EncounterInProgress,
        Instance_Full,
        Housing_CrateFull,
        TargetBusy,
        Mail_CannotReturn               = 119,
        Mail_CannotMailSelf             = 120,
        Faction_AtMax,
        Housing_MaxDecor,
        Auction_ItemAuctionDisabled,
        Auction_CommodityDisabled,
        Mail_CannotMailTrialAccount     = 125,
        MissingEntitlement              = 126,
        Instance_TransferPending,
        Instance_InvalidDestination,
        Instance_NotInGroup,
        Instance_DifferentSavedInstance,
        Instance_InstanceInUse,
        Item_WrongFaction,
        Instance_WrongLevel,
        Mail_Squelched                  = 134,
        LootForge_QualityMismatch,
        LootForge_InvalidItem,
        LootForge_CountMismatch,
        LootForge_Invalid,
        RewardTrack_CannotClaim,
        RewardTrack_InvalidRewardChoice,
        RewardTrack_InvalidTrackChoice,
        RewardTrack_TrackNotActive,
        RewardTrack_TrackAlreadyActive,
        Item_EquipPrereqFailed,
        Instance_PenaltyMap,
        Auction_TooManyBids,
        AccountItem_MaxEntitlementCount,
        Item_BadParams,
        Item_BadStaticData,
        Craft_TooFar,
        Craft_InvalidTier,
        Craft_BadId,
        Craft_BadParams,
        Craft_InvalidPowerCore,
        RewardTrack_Locked,
        Item_CannotBeDeleted,
        MTXChest_AlreadyOpened,
        Mail_CannotSendAttachments      = 158,
        ExceedsMoneyTradeLimit          = 159,
        Mail_LevelRequirement           = 161,
        Path_AlreadyUnlocked,
        Path_InsufficientFunds,
        PathChange_InsufficientFunds,
        PathChange_NotUnlocked,
        PathChange_OnCooldown,
        PathChange_Requested,
        PathUnlock_Requested,
        InvalidGenericUnlock            = 172,
        GenericUnlock_AlreadyUnlocked,
        Housing_CommunityMaxDecor
    }
}