namespace NexusForever.WorldServer.Game.Combat.Static
{
    public enum CombatLogType
    {
        Absorption           = 0,
        CCState              = 1,
        CCStateBreak         = 2,
        Damage               = 3,
        DamageShields        = 4,
        Reflect              = 5,
        MultiHit             = 6,
        MultiHitShields      = 7,
        FallingDamage        = 8,
        Lifesteal            = 9,
        DelayDeath           = 10,
        Dispel               = 11,
        Heal                 = 12,
        MultiHeal            = 13,
        ModifyInterruptArmor = 14,
        Transference         = 15,
        VitalModifier        = 16,
        Deflect              = 17,
        Immune               = 18,
        Interrupted          = 19,
        KillStreak           = 20,
        KillPvP              = 21,
        Death                = 22,
        Resurrect            = 23,
        Stealth              = 24,
        Mount                = 25,
        Pet                  = 26,
        Experience           = 27,
        Modifying            = 28,
        DurabilityLoss       = 29,
        Crafting             = 30,
        LAS                  = 31,
        BuildSwitch          = 32,
        Datacube             = 33,
        HealingAbsorption    = 35,
    }
}
